basePath: /
definitions:
  cart.AddToCartRequest:
    properties:
      productId:
        type: string
    type: object
  cart.Cart:
    properties:
      createdAt:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/cart.CartItem'
        type: array
      totalPrice:
        format: float64
        type: number
      updatedAt:
        type: string
      userID:
        type: string
    type: object
  cart.CartItem:
    properties:
      cartID:
        type: string
      id:
        type: string
      price:
        format: float64
        type: number
      productID:
        type: string
      quantity:
        type: integer
    type: object
  cart.RemoveFromCartRequest:
    properties:
      productId:
        type: string
    type: object
  cart.UpdateQuantityRequest:
    properties:
      productId:
        type: string
      type:
        description: '"increase" ya "decrease"'
        type: string
    type: object
  order.CreateOrderRequest:
    properties:
      amount:
        type: number
      currency:
        type: string
      products:
        items:
          $ref: '#/definitions/order.OrderItemRequest'
        type: array
      shipping:
        type: number
      tax:
        type: number
    type: object
  order.OrderItemRequest:
    properties:
      price:
        type: number
      productId:
        type: string
      quantity:
        type: integer
    type: object
  order.VerifyPaymentRequest:
    properties:
      paymentFailed:
        type: boolean
      razorpay_order_id:
        type: string
      razorpay_payment_id:
        type: string
      razorpay_signature:
        type: string
    type: object
  product.ProductImageResponse:
    properties:
      public_id:
        type: string
      url:
        type: string
    type: object
  product.ProductResponse:
    properties:
      brand:
        type: string
      category:
        type: string
      id:
        type: string
      productDesc:
        type: string
      productImg:
        items:
          $ref: '#/definitions/product.ProductImageResponse'
        type: array
      productName:
        type: string
      productPrice:
        type: number
    type: object
  user.ChangePasswordRequest:
    properties:
      confirmPassword:
        type: string
      newPassword:
        type: string
    type: object
  user.ForgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.LoginResponse:
    properties:
      refreshToken:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserResponse'
    type: object
  user.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  user.UpdateUserRequest:
    properties:
      address:
        type: string
      city:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phoneNo:
        type: string
      role:
        type: string
      zipCode:
        type: string
    type: object
  user.UserResponse:
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      isLoggedIn:
        type: boolean
      isVerified:
        type: boolean
      lastName:
        type: string
      phoneNo:
        type: string
      profilePic:
        type: string
      refreshToken:
        type: string
      role:
        type: string
      token:
        type: string
      zipCode:
        type: string
    type: object
  user.VerifyOTPRequest:
    properties:
      email:
        type: string
      otp:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Ekart server.
  title: Ekart API
  version: "1.0"
paths:
  /cart:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.Cart'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get cart
      tags:
      - Cart
    post:
      consumes:
      - application/json
      parameters:
      - description: Cart payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cart.AddToCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Add to cart
      tags:
      - Cart
  /cart/remove:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cart removal payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cart.RemoveFromCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Remove from cart
      tags:
      - Cart
  /cart/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: Cart update payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/cart.UpdateQuantityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.Cart'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update quantity in cart
      tags:
      - Cart
  /orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: Order payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/order.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create order
      tags:
      - Order
  /orders/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: Payment verification payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/order.VerifyPaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Verify payment
      tags:
      - Order
  /products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product.ProductResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all products
      tags:
      - Product
  /products/{productId}:
    delete:
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete product
      tags:
      - Product
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: string
      - description: Product name
        in: formData
        name: name
        type: string
      - description: Product description
        in: formData
        name: description
        type: string
      - description: Product price
        format: float64
        in: formData
        name: price
        type: number
      - description: Product stock
        in: formData
        name: stock
        type: integer
      - description: Product images (multiple allowed)
        in: formData
        name: files
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update product
      tags:
      - Product
  /products/add:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Product name
        in: formData
        name: name
        required: true
        type: string
      - description: Product description
        in: formData
        name: description
        required: true
        type: string
      - description: Product price
        format: float64
        in: formData
        name: price
        required: true
        type: number
      - description: Product stock
        in: formData
        name: stock
        required: true
        type: integer
      - description: Product images (multiple allowed)
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Add product
      tags:
      - Product
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - User
  /users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - User
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update user payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - User
  /users/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Change password payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Change password
      tags:
      - User
  /users/forgot-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Forgot password payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Forgot password
      tags:
      - User
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - User
  /users/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - User
  /users/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get profile
      tags:
      - User
    put:
      consumes:
      - application/json
      parameters:
      - description: Update user payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update profile
      tags:
      - User
  /users/register:
    post:
      consumes:
      - application/json
      description: Naya user register karo
      parameters:
      - description: Register payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register user
      tags:
      - User
  /users/verify-otp/{email}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Verify OTP payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Verify OTP
      tags:
      - User
swagger: "2.0"
